Feat board api
yangyag/toy_projects pull request #3
Opened 2022-02-11 15:21 UTC by yangyag

2022-02-12 05:16 UTC, bbuljj requested changes
리뷰 달았습니다. 수정 해주시고, 
추가적으로 PostService에 대한 테스트가 없네요 PostServiceTest도 추가해주시고 이 서비스는 Mock으로만 해주시면 됩니다.

2022-02-12 05:16 UTC, bbuljj commented on src/main/java/com/yangyag/toy/service/PostService.java
> +    @Transactional
read 인데 `Transactional` 을 붙힌 이유가 궁금합니다.

2022-02-12 05:16 UTC, bbuljj commented on src/main/java/com/yangyag/toy/service/PostService.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당 게시물이 없습니다"));;
데이터가 없을 경우 `NotFoundException` 으로 해주세요.
RuntimeException을 상속하는  NotFoundException 를 생성해주면 더 좋을 것 같습니다.

추가적으로 @ControllerAdvice 를 찾아보시고 ExceptionHandler에 대한 부분도 추가해주세요.
각 Exception별로 관리할 수 있어 편리합니다.

2022-02-12 05:16 UTC, bbuljj commented on src/main/java/com/yangyag/toy/service/PostService.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당 게시물이 없습니다"));
여기도 마찬가지로 `NotfoundException`

2022-02-12 05:16 UTC, bbuljj commented on src/main/java/com/yangyag/toy/service/PostService.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당 게시물이 없습니다"));
여기도 `Notfound~`

2022-02-12 05:16 UTC, bbuljj commented on src/main/java/com/yangyag/toy/web/PostController.java
> +        return new ResponseEntity<>(id, HttpStatus.CREATED);
`new ResponseEntity<>` 나쁘진 않지만
`ResponseEntity.create`를 사용하거나 `ResponseEntity.status(HttpStatus.CREATED)`를 사용하는게 가독성도 좋아보이고 코드도 깔끔해질 것 같아요

2022-02-12 05:16 UTC, bbuljj commented on src/main/java/com/yangyag/toy/web/PostController.java
> +    @PostMapping()
필요없는 `()` 는 지워주세요

2022-02-12 05:16 UTC, bbuljj commented on src/main/java/com/yangyag/toy/web/PostController.java
> +    public ResponseEntity<Object> createPost(PostSaveRequest postSaveRequest) throws Exception {
`@Valid` 를 추가해서 초기 값들의 validation 을 수행해주세요

2022-02-12 05:16 UTC, bbuljj commented on src/main/java/com/yangyag/toy/web/PostController.java
> +        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
Delete 성공은 HttpStatus.OK 입니다.

2022-02-12 05:16 UTC, bbuljj commented on src/main/java/com/yangyag/toy/web/dto/PostSaveRequest.java
> +@Data
`Data`에는 EqualsHashCode가 포함되는데 현재 DTO에는 필요없어보입니다.
@Getter @Setter로 대체해주세요

2022-02-14 00:26 UTC, yangyag commented
> 리뷰 달았습니다. 수정 해주시고, 추가적으로 PostService에 대한 테스트가 없네요 PostServiceTest도 추가해주시고 이 서비스는 Mock으로만 해주시면 됩니다.

네 알겠습니다

2022-02-14 00:27 UTC, yangyag commented on src/main/java/com/yangyag/toy/service/PostService.java
> +    @Transactional
제거 하도록 하겠습니다

2022-02-14 00:28 UTC, yangyag commented on src/main/java/com/yangyag/toy/service/PostService.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당 게시물이 없습니다"));;
넵

2022-02-14 00:28 UTC, yangyag commented on src/main/java/com/yangyag/toy/service/PostService.java
> +                .orElseThrow(() -> new IllegalArgumentException("해당 게시물이 없습니다"));
넵

2022-02-14 00:32 UTC, yangyag commented on src/main/java/com/yangyag/toy/web/PostController.java
> +        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
넵

2022-02-14 00:33 UTC, yangyag commented on src/main/java/com/yangyag/toy/web/PostController.java
> +    @PostMapping()
아 그렇네요

2022-02-14 00:33 UTC, yangyag commented on src/main/java/com/yangyag/toy/web/PostController.java
> +    public ResponseEntity<Object> createPost(PostSaveRequest postSaveRequest) throws Exception {
넵

2022-02-14 00:36 UTC, yangyag commented on src/main/java/com/yangyag/toy/web/PostController.java
> +        return new ResponseEntity<>(id, HttpStatus.CREATED);
네 바꿔보겠습니다

2022-02-14 00:36 UTC, yangyag commented on src/main/java/com/yangyag/toy/web/dto/PostSaveRequest.java
> +@Data
네 알겠습니다

2022-02-15 09:26 UTC, bbuljj commented on src/main/java/com/yangyag/toy/web/PostController.java
> +        var list = postService.getList(pageRequest);
`Pageable` 을 그대로 던져주면 끝납니다.

2022-02-15 09:26 UTC, bbuljj commented on src/main/java/com/yangyag/toy/web/PostController.java
> +        var list = postService.getList(pageRequest);
`getLIst(pageable);`

2022-02-15 09:26 UTC, bbuljj commented on src/test/java/com/yangyag/toy/service/PostServiceTest.java
> +        then(postRepository).should(atLeastOnce()).findAll(pageRequest);
위 테스트에 Page 데이터가 실제 있는지에 대한 테스트를 추가해주세요.

2022-02-15 09:26 UTC, bbuljj commented on src/test/java/com/yangyag/toy/web/PostControllerTest.java
> +    }
보통이렇게 set하지 않습니다. BeforeEach 는 각 테스트가 수행될 때마다 실행되는 초기 메소드라
30 * 메소드 갯수 가 수행되겠네요. 데이터를 넣어서 하는거보단 Page 객체가 Response에 포함되는지 테스트를 하면 의도가 더 명확할 듯 합니다. Response 포함 테스트는 `mockMvc.perform().andExpect(jsonPath("$.data").isEmpty())` 이런식으로 $.data에 값이 있는 지에 대한 테스트를 해주시면 됩니다.

2022-02-15 09:26 UTC, bbuljj commented on src/test/java/com/yangyag/toy/web/PostControllerTest.java
> +                .perform(get("/posts?size=" + size + "&page=" + page))
URI에 `String`을 하드코딩 하지마시고, `get().params()` 에 포함시켜서 타입세이프하게 작성해주세요.

2022-02-15 09:29 UTC, yangyag commented on src/main/java/com/yangyag/toy/web/PostController.java
> +        var list = postService.getList(pageRequest);
네 수정하겠습니다.

2022-02-15 09:29 UTC, yangyag commented on src/test/java/com/yangyag/toy/service/PostServiceTest.java
> +        then(postRepository).should(atLeastOnce()).findAll(pageRequest);
넵

2022-02-15 09:29 UTC, yangyag commented on src/test/java/com/yangyag/toy/web/PostControllerTest.java
> +    }
안그래도 이부분을 어떻게 해야 고민했는데.. 알겠습니다!

2022-02-15 09:29 UTC, yangyag commented on src/test/java/com/yangyag/toy/web/PostControllerTest.java
> +                .perform(get("/posts?size=" + size + "&page=" + page))
넵

2022-02-16 08:54 UTC, bbuljj commented on src/main/java/com/yangyag/toy/domain/reply/Reply.java
> +    @Column(name = "post_id", nullable = false)
nullable = false 를 사용하게되면 Database Validation 에 의존하기 때문에 ORM에 지향하는 부분을 커버할 수 없습니다. 
`nullable=false`를 제거하는게 바람직하고, Lombok의 NonNull이 아닌 Java Bean Validation `@NotNull` 을 사용하는게 더 유용합니다.
https://kafcamus.tistory.com/15

2022-02-16 08:55 UTC, bbuljj requested changes

2022-02-16 08:55 UTC, bbuljj commented on src/main/java/com/yangyag/toy/domain/reply/Reply.java
> +    @Column(nullable = false)
여기도 위와마찬가지로 수정해주세요.

2022-02-16 12:14 UTC, yangyag commented on src/main/java/com/yangyag/toy/domain/reply/Reply.java
> +    @Column(name = "post_id", nullable = false)
아.. 네 감사합니다

2022-02-16 12:14 UTC, yangyag commented on src/main/java/com/yangyag/toy/domain/reply/Reply.java
> +    @Column(nullable = false)
넵

2022-02-21 03:14 UTC, bbuljj approved these changes
리뷰양이 많아서 먼저 머지 후 진행.

2022-02-21 04:10 UTC, merged